
# Analysis for Study 1
# This code performs the analysis using MICE with unweighted PMM


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, fig.show = "hide", eval = FALSE)

# fig.show='hide', eval=FALSE
```

# Loading packages

```{r package loading}
# Set up renv for package management
if (!requireNamespace("renv", quietly = TRUE)) {
    install.packages("renv")
}

# Load the renv package
library(renv)

# Check if renv is already active, activate if not
if (!renv::status()$synchronized) {
    renv::activate()
}

# To restore the environment (for a collaborator)
renv::restore()

required_packages <- c(
    "expss", "ggmice", "ggplot2", "haven", "howManyImputations", "mice",
    "modelsummary", "NCmisc", "readxl", "stats", "tidyr", "utils"
)

## Load the required packages
for (package in required_packages) {
    library(package, character.only = TRUE)
}

# Adjust settings for specific packages
if ("survey" %in% installed.packages()[, "Package"]) {
    options(survey.lonely.psu = "adjust")
}
```

# Data handling
## Loading data and creating subset

```{r Data load and subsetting}
# Load the children dataset from a .SAV file
## depending on computer  "C:/Users/Rik/OneDrive/PhD_Undernutrition_Uganda_Physical_Accessbility/1_Study_1_Physical_access/Data/DATA/Uganda Full/DHS Clusters/UGKR7BSV_Children/UGKR7BFL.SAV"
##                        "D:/Onedrive/PhD_Undernutrition_Uganda_Physical_Accessbility/1_Study_1_Physical_access/Data/DATA/Uganda Full/DHS Clusters/UGKR7BSV_Children/UGKR7BFL.SAV"

DHS_children_sub <- read_sav("D:/Onedrive/PhD_Undernutrition_Uganda_Physical_Accessbility/1_Study_1_Physical_access/Data/DATA/Uganda Full/DHS Clusters/UGKR7BSV_Children/UGKR7BFL.SAV") %>%
    dplyr::select(
        CASEID,
        V001, V005,
        V023, V024,
        V149, V729,
        V191, V212,
        V445, V714,
        BIDX, B0, B4,
        B5, BORD,
        HW5, HW8,
        HW11, M19,
        B11, H11,
        V113, M5,
        V136,
        V481, H22,
        V505, H7
    )

# Load the travel time data from an Excel file
## Depending on computer    "C:/Users/Rik/OneDrive/PhD_Undernutrition_Uganda_Physical_Accessbility/1_Study_1_Physical_access/Data/DATA/Uganda Full/Travel_Time/Travel_time.xls"
##                          "D:/Onedrive/PhD_Undernutrition_Uganda_Physical_Accessbility/1_Study_1_Physical_access/Data/DATA/Uganda Full/Travel_Time/Travel_time.xls"
Travel_time_clust <- read_xls("D:/Onedrive/PhD_Undernutrition_Uganda_Physical_Accessbility/1_Study_1_Physical_access/Data/DATA/Uganda Full/Travel_Time/Travel_time.xls",
    col_names = TRUE
)


# Merge the children dataset with the travel time data using the common column "V001" in both datasets
DHS_children_sub <- merge(DHS_children_sub, Travel_time_clust,
    by.x = "V001",
    by.y = "DHSCLUST"
)


# Convert the NEAR_DIST column from meters to kilometers
DHS_children_sub$NEAR_DIST <- DHS_children_sub$NEAR_DIST / 1000
```

#### Removing unnecessary SPSS metadata

```{r removing metadata}
# Remove unnecessary SPSS metadata from the children dataset
## Remove variable formats
DHS_children_sub <- zap_formats(DHS_children_sub)

## Remove variable widths
DHS_children_sub <- zap_widths(DHS_children_sub)

## Remove variable labels
DHS_children_sub <- zap_labels(DHS_children_sub)

## Remove variable label
DHS_children_sub <- zap_label(DHS_children_sub)
```

## Defining missing data
```{r missing data}
# Replace specific values with NA (missing data) in various columns
## For column HW5, replace 9998 and 9999 with NA
DHS_children_sub$HW5[DHS_children_sub$HW5 == 9998] <- NA
DHS_children_sub$HW5[DHS_children_sub$HW5 == 9999] <- NA

## For column HW8, replace 9998 and 9999 with NA
DHS_children_sub$HW8[DHS_children_sub$HW8 == 9998] <- NA
DHS_children_sub$HW8[DHS_children_sub$HW8 == 9999] <- NA

## For column HW11, replace 9998 and 9999 with NA
DHS_children_sub$HW11[DHS_children_sub$HW11 == 9998] <- NA
DHS_children_sub$HW11[DHS_children_sub$HW11 == 9999] <- NA

## For column V149, replace 9 with NA
DHS_children_sub$V149[DHS_children_sub$V149 == 9] <- NA

## For column V729, replace 9 with NA
DHS_children_sub$V729[DHS_children_sub$V729 == 9] <- NA

## For column V445, replace 9998 and 9999 with NA
DHS_children_sub$V445[DHS_children_sub$V445 == 9998] <- NA
DHS_children_sub$V445[DHS_children_sub$V445 == 9999] <- NA

## For column V714, replace 9 with NA
DHS_children_sub$V714[DHS_children_sub$V714 == 9] <- NA

## For column M19, replace 9996, 9998, and 9999 with NA
DHS_children_sub$M19[DHS_children_sub$M19 == 9996] <- NA
DHS_children_sub$M19[DHS_children_sub$M19 == 9998] <- NA
DHS_children_sub$M19[DHS_children_sub$M19 == 9999] <- NA

## For column H11, replace 8 and 9 with NA
DHS_children_sub$H11[DHS_children_sub$H11 == 8] <- NA
DHS_children_sub$H11[DHS_children_sub$H11 == 9] <- NA

## For column M5, replace 93, 94, 97, 98, and 99 with NA
DHS_children_sub$M5[DHS_children_sub$M5 == 93] <- NA
DHS_children_sub$M5[DHS_children_sub$M5 == 94] <- NA
DHS_children_sub$M5[DHS_children_sub$M5 == 97] <- NA
DHS_children_sub$M5[DHS_children_sub$M5 == 98] <- NA
DHS_children_sub$M5[DHS_children_sub$M5 == 99] <- NA

## For column V113, replace 99, 97, and 96 with NA
DHS_children_sub$V113[DHS_children_sub$V113 == 99] <- NA
DHS_children_sub$V113[DHS_children_sub$V113 == 97] <- NA
DHS_children_sub$V113[DHS_children_sub$V113 == 96] <- NA

## For column H7, replace 8 and 9 with NA
DHS_children_sub$H7[DHS_children_sub$H7 == 8] <- NA
DHS_children_sub$H7[DHS_children_sub$H7 == 9] <- NA

## For column V481, replace 9 with NA
DHS_children_sub$V481[DHS_children_sub$V481 == 9] <- NA

## For column H22, replace 8 and 9 with NA
DHS_children_sub$H22[DHS_children_sub$H22 == 8] <- NA
DHS_children_sub$H22[DHS_children_sub$H22 == 9] <- NA

## For column V505, replace 98 and 99 with NA
DHS_children_sub$V505[DHS_children_sub$V505 == 98] <- NA
DHS_children_sub$V505[DHS_children_sub$V505 == 99] <- NA
```

## Recoding variables

```{r recoding}
# Transforming variables into more interpretable formats
## Birth interval: Dichotomize into more or less than 24 months
DHS_children_sub$B11 <- ifelse(DHS_children_sub$B11 >= 24, 0, 1)

## Combined diarrhea in the last 24 hours and 2 weeks into one category
DHS_children_sub$H11 <- ifelse(DHS_children_sub$H11 == 0, 0, 1)

## Recode source of drinking water into simplified categories
DHS_children_sub$V113 <- expss::recode(
    DHS_children_sub$V113,
    11 %thru% 14 ~ 1, 21 ~ 2, 31 %thru% 32 ~ 3, 41 %thru% 43 ~ 4, 51 ~ 5, 63 ~ 6, 71 ~ 6
)

## Convert the variables into factors
DHS_children_sub$B11 <- factor(DHS_children_sub$B11,
    levels = c(0, 1),
    labels = c("Birth interval more than 24 months", "Birth interval less than 24 months")
)

DHS_children_sub$H11 <- factor(DHS_children_sub$H11,
    levels = c(0, 1),
    labels = c("No diarrhea in the last 2 weeks", "Had diarrhea in the last 2 weeks")
)

## Recode the sex of the child
DHS_children_sub$B4 <- ifelse(DHS_children_sub$B4 == 1, 0, 1) %>% factor(levels = c(0, 1), labels = c("Male", "Female"))

## Create a factor for twin births
DHS_children_sub$B0 <- factor(DHS_children_sub$B0,
    levels = c(0:3),
    labels = c("Single Birth", "1st of multiple", "2nd of multiple", "3rd of multiple")
)

## Recode DPT 3 into yes and no answers and make it a factor
DHS_children_sub$H7 <- ifelse(DHS_children_sub$H7 == 0, 0, 1)
DHS_children_sub$H7 <- factor(DHS_children_sub$H7,
    levels = c(0, 1),
    labels = c("No have not received", "Yes, received DPT 3")
)

## Set other variables as factors
DHS_children_sub$V149 <- factor(DHS_children_sub$V149,
    levels = c(0, 1, 2, 3, 4, 5),
    labels = c("No education", "Incomplete Primary", "Complete primary", "Incomplete secondary", "Complete secondary", "Higher")
)

DHS_children_sub$V729 <- factor(DHS_children_sub$V729,
    levels = c(0, 1, 2, 3, 4, 5),
    labels = c("No education", "Incomplete Primary", "Complete primary", "Incomplete secondary", "Complete secondary", "Higher")
)

DHS_children_sub$V714 <- factor(DHS_children_sub$V714,
    levels = c(0, 1),
    labels = c("Not working", "Currently working")
)

DHS_children_sub$V113 <- factor(DHS_children_sub$V113,
    levels = c(1, 2, 3, 4, 5, 6),
    labels = c("Piped Water", "Tube Well Water", "Dug Well (Open/Protected", "Surface from Spring", "Rainwater", "Other")
)

DHS_children_sub$V481 <- factor(DHS_children_sub$V481,
    levels = c(0, 1),
    labels = c("No", "Yes")
)

DHS_children_sub$H22 <- factor(DHS_children_sub$H22,
    levels = c(0, 1),
    labels = c("No", "Yes")
)

## Scaling certain variables for better interpretation
DHS_children_sub$HW5 <- DHS_children_sub$HW5 / 100
DHS_children_sub$HW8 <- DHS_children_sub$HW8 / 100
DHS_children_sub$HW11 <- DHS_children_sub$HW11 / 100
DHS_children_sub$V445 <- DHS_children_sub$V445 / 100
DHS_children_sub$V191 <- DHS_children_sub$V191 / 1000

## Create categorical variables for stunting, underweight, wasting, severe acute malnutrition, region, and travel time
DHS_children_sub$HW5_cat <- ifelse(DHS_children_sub$HW5 >= -2, 0, 1) %>%
    factor(
        levels = c(0, 1),
        labels = c("Not stunted", "Stunted")
    )

DHS_children_sub$HW8_cat <- ifelse(DHS_children_sub$HW8 >= -2, 0, 1) %>%
    factor(
        levels = c(0, 1),
        labels = c("Not underweight", "Underweight")
    )

DHS_children_sub$HW11_cat <- ifelse(DHS_children_sub$HW11 >= -2, 0, 1) %>%
    factor(
        levels = c(0, 1),
        labels = c("Not wasted", "Wasted")
    )

DHS_children_sub$SAM <- ifelse(DHS_children_sub$HW11 >= -3, 0, 1) %>%
    factor(
        levels = c(0, 1),
        labels = c("Not SAM", "SAM")
    )

DHS_children_sub$V024 <- factor(DHS_children_sub$V024,
    levels = c(0:14),
    labels = c("Kampala", "South Buganda", "North Buganda", "Busoga", "Bukedi", "Bugisu", "Teso", "Karamoja", "Lango", "Acholi", "West Nile", "Bunyoro", "Tooro", "Ankole", "Kigezi")
)

## Rename the Travel time variable
DHS_children_sub <- dplyr::rename(DHS_children_sub, travel_time = raster_travel_time_Lower_travel_time_V1)

## Create a categorical variable for travel time
DHS_children_sub$travel_time_cat <- expss::recode(
    DHS_children_sub$travel_time,
    0 %thru% 30 ~ 1,
    31 %thru% 60 ~ 2,
    61 %thru% 120 ~ 3,
    121 %thru% 999 ~ 4
) %>%
    factor(
        levels = c(1, 2, 3, 4),
        labels = c("30 min. or less", "30 - 60 min.", "1 -2 hours", "More than 2 hours")
    )

Travel_time_clust$travel_time_cat <- expss::recode(
    Travel_time_clust$raster_travel_time_Lower_travel_time_V1,
    0 %thru% 30 ~ 1,
    31 %thru% 60 ~ 2,
    61 %thru% 120 ~ 3,
    121 %thru% 999 ~ 4
) %>%
    factor(
        levels = c(1, 2, 3, 4),
        labels = c("30 min. or less", "30 - 60 min.", "1 -2 hours", "More than 2 hours")
    )
```

## Providing labels

```{r providing labels}
# Assigning variable labels to the dataset
var_lab(DHS_children_sub$V001) <- "Cluster number"
var_lab(DHS_children_sub$V005) <- "Women's individual sample weight"
var_lab(DHS_children_sub$V023) <- "Stratification used in sample design"
var_lab(DHS_children_sub$BORD) <- "Birth order"
var_lab(DHS_children_sub$V149) <- "Educational attainment of the mother"
var_lab(DHS_children_sub$V729) <- "Educational attainment of the father"
var_lab(DHS_children_sub$V191) <- "Wealth index"
var_lab(DHS_children_sub$V212) <- "Age of respondent at first birth"
var_lab(DHS_children_sub$V445) <- "BMI of mother (kg/m^2)"
var_lab(DHS_children_sub$V714) <- "Work status of mother"
var_lab(DHS_children_sub$B4) <- "Sex of child"
var_lab(DHS_children_sub$HW5) <- "Stunting (continious)"
var_lab(DHS_children_sub$HW8) <- "Underweight (continious)"
var_lab(DHS_children_sub$HW11) <- "Wasting (continious)"
var_lab(DHS_children_sub$V024) <- "Region"
var_lab(DHS_children_sub$M19) <- "Birth weight in grams"
var_lab(DHS_children_sub$M5) <- "Duration of breastfeeding"
var_lab(DHS_children_sub$V113) <- "Source of drinking water"
var_lab(DHS_children_sub$V136) <- "Number of household members"
var_lab(DHS_children_sub$V481) <- "Covered by health insurance"
var_lab(DHS_children_sub$H22) <- "Fever last two weeks"
var_lab(DHS_children_sub$V505) <- "Number of other wives"
var_lab(DHS_children_sub$V714) <- "Mother is currently working"
var_lab(DHS_children_sub$V729) <- "Education of father/partner"
var_lab(DHS_children_sub$V024) <- "Region of residence"
var_lab(DHS_children_sub$SAM) <- "SAM categorical"
var_lab(DHS_children_sub$V149) <- "Education of mother"
var_lab(DHS_children_sub$B4) <- "Sex"
var_lab(DHS_children_sub$H11) <- "Had diarrhea in the last two weeks"
var_lab(DHS_children_sub$B11) <- "Preceding birth interval <=24"
var_lab(DHS_children_sub$B0) <- "Child is twin"
var_lab(DHS_children_sub$HW11_cat) <- "Wasted categorical"
var_lab(DHS_children_sub$HW8_cat) <- "Underweight categorical"
var_lab(DHS_children_sub$HW5_cat) <- "Stunting categorical"
var_lab(DHS_children_sub$travel_time) <- "Travel Time in min."
var_lab(DHS_children_sub$URBAN_RURA) <- "Cluster type urban/rural"
var_lab(DHS_children_sub$NEAR_DIST) <- "Distance to nearest HC facility in km."
var_lab(DHS_children_sub$H7) <- "Child has received DPT3 vaccination"
var_lab(DHS_children_sub$travel_time_cat) <- "Travel Time Categorical"
var_lab(Travel_time_clust$travel_time_cat) <- "Travel Time Categorical"
```

## Removing invalid data

```{r removing invalid data}
# Removing invalid data
## Filter out rows with children who are no longer alive (B5 == 1)
DHS_children_sub <- subset(DHS_children_sub, B5 == 1)

## Keep only children with anthropometric measurements (non-missing HW5 values)
DHS_children_sub <- DHS_children_sub %>% drop_na(HW5)
```

# Imputing missing data

```{r imputing missing data}
# Imputing Data using Multiple Imputation by Chained Equation (MICE)

# We followed the two-step recipe for imputation from von Hippel (2018) to determine the number of imputations needed for our data. The two-step recipe is as follows:
#   1. Carry out a pilot analysis. Impute the data using a convenient number of imputations. (20 imputations is a reasonable default, if it doesn’t take too long.) Estimate the FMI by analyzing the imputed data.
#   2. Plug the estimated FMI into the formula above to figure out how many imputations you need to achieve a certain value of CV(SE). If you need more imputations than you had in the pilot, then add those imputations and analyze the data again.
# https://statisticalhorizons.com/how-many-imputations/

## Create a predictor matrix for imputation
pred_mat <- quickpred(DHS_children_sub, mincor = 0.25)

## Two-step recipe for imputation, first we do a pilot analysis with 20 imputations and then we calculate the number of imputations needed (see # MICE models unweighted below))
### MaxIt already converged at 5 iterations so no need to increase the number of iterations
DHS_children_sub_multimp <- mice(DHS_children_sub,
    m = 150,
    predictorMatrix = pred_mat,
    set.seed = 123,
    method = "pmm"
)

# Check the quality of imputations by visualizing imputed data distribution
## Density plot for all variables
ggmice(DHS_children_sub_multimp, aes(M5)) +
    geom_boxplot()

```

# Statistical testing
## MICE models unweighted

```{r MICE Pooled unweighted}
# Models for Stunting, Wasting, and Underweight using MICE
## Stunting
MICE_model_stunt <- with(
    DHS_children_sub_multimp,
    lm(HW5 ~ B4 + BORD + M19 + B11 + H11 + H22 + V481 + V729 + V505 + V191 + V212 + V445 + V714 + V113 + V136 + M5 + H7 + travel_time, )
)

modelsummary(pool(MICE_model_stunt),
    stars = TRUE,
    coef_rename = TRUE,
    coef_omit = "^(?!trav)",
    gof_omit = ".*",
    conf_level = 0.95,
    fmt = fmt_significant(2),
    statistic = "{p.value} [{conf.low}, {conf.high}]",
    notes = "All estimates for travel time are based on pooled data from multiple imputation analysis and are corrected for other covariates."
)

## Wasting
MICE_model_wast <- with(
    DHS_children_sub_multimp,
    lm(HW11 ~ B4 + BORD + M19 + B11 + H11 + H22 + V481 + V729 + V505 + V191 + V212 + V445 + V714 + V113 + V136 + M5 + H7 + travel_time, )
)

modelsummary((pool(MICE_model_wast)),
    stars = TRUE,
    coef_rename = T
)

modelsummary(pool(MICE_model_wast),
    stars = TRUE,
    coef_rename = TRUE,
    coef_omit = "^(?!trav)",
    gof_omit = ".*",
    conf_level = 0.95,
    fmt = fmt_significant(2),
    statistic = "{p.value} [{conf.low}, {conf.high}]",
    notes = "All estimates for travel time are based on pooled data from multiple imputation analysis and are corrected for other covariates."
)

## Underweight
MICE_model_underweight <- with(
    DHS_children_sub_multimp,
    lm(HW8 ~ B4 + BORD + M19 + B11 + H11 + H22 + V481 + V729 + V505 + V191 + V212 + V445 + V714 + V113 + V136 + M5 + H7 + travel_time, )
)

modelsummary((pool(MICE_model_underweight)),
    stars = TRUE,
    coef_rename = T
)

modelsummary(pool(MICE_model_underweight),
    stars = TRUE,
    coef_rename = TRUE,
    coef_omit = "^(?!trav)",
    gof_omit = ".*",
    conf_level = 0.95,
    fmt = fmt_significant(2),
    statistic = "{p.value} [{conf.low}, {conf.high}]",
    notes = "All estimates for travel time are based on pooled data from multiple imputation analysis and are corrected for other covariates."
)

# Based on the how_many)imputations package based on Von Hippel we need about 150 imputations
how_many_imputations(MICE_model_stunt)
how_many_imputations(MICE_model_wast)
how_many_imputations(MICE_model_underweight)
```